name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  lucide_icons: ^0.257.0
  fl_chart: ^0.66.2
  intl: ^0.18.1
  google_maps_flutter: ^2.12.3
  geolocator: ^10.1.0
  permission_handler: ^11.3.0
  image_picker: ^1.1.2
  google_sign_in: ^6.3.0
  multi_select_flutter: ^4.1.3
  logger: ^2.6.0
  image: ^4.5.4
  uuid: ^4.5.1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8

  firebase_core: ^3.13.1
  firebase_app_check: ^0.3.2+10
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.10
  provider: ^6.1.5
  firebase_storage: ^12.4.10
  url_launcher: ^6.3.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0
  http: ^1.5.0
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/waste.png"
  adaptive_icon_background: "#c5fac5"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/user_avatar.jpg
    - assets/waste.png
    - assets/splas_logo.jpg
    - assets/Chatgpt_image.png
